name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]          # or your default branch

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20       # any LTS ≥18 works
          cache: "pnpm"          # cache the pnpm store

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9             # or “latest”
          run_install: true      # runs `pnpm install` for you

      - name: Build Astro site
        run: pnpm run build      # uses pnpm, respects your lockfile

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./dist
